version: '3.7'
services:
  postgres-db:
    container_name: postgres-container
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=customerUser'
      - 'POSTGRES_PASSWORD=customerPassword'


  customer:
    build: ./
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=development-postgresql'
      - 'POSTGRES_HOST=postgres-db'
    depends_on:
      - postgres-db

