version: '3.7'
services:
  postgres-db:
    image: postgres:12
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=customerUser'
      - 'POSTGRES_PASSWORD=customerPassword'
  customer:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-image
    container_name: customer-container
    expose:
      - "8080/tcp"
      - "5005/tcp"
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - 'WAIT_HOSTS=postgres:5432'
      - 'SPRING_PROFILES_ACTIVE=development-postgresql'
      - 'POSTGRES_HOST=postgres-db'
    depends_on:
      - postgres-db

