# Default properties
spring:
  profiles:
    active: development-local
  output:
    ansi:
      enabled: always
  cloud:
    refresh:
      refreshable: none

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true

logging:
  level.io.fdlessard.codebites.customer: DEBUG
#  level.root: DEBUG

---
# Development profile

spring:
  profiles: development-local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    data: classpath:data/data-h2.sql
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console
#  datasource:
#    platform: POSTGRESQL
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: create-drop

