server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true

logging:
  level.root: INFO
  #  level.org.hibernate.SQL: DEBUG
  level.io.fdlessard.codebites.customer: DEBUG


spring:
  output:
    ansi:
      enabled: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
  datasource:
    username: postgres
    password: secret
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    initialization-mode: always
    data: classpath:data/data.sql





